server:
  port: 8004

spring:
  application:
    name: cloud-payment-service #微服务的名称，设定完成之后，最好不要改动

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.0.113:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.binc.springCloud.entities

eureka:
  client:
    #表示是否将自己注册到eurekaserver，默认true
    register-with-eureka: true
    #是否从eurekaserver抓取已有的注册信息，默认true；单节点的无所谓，集群的必须设置为true ，才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: 111http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #将服务这测到eureka集群的堕胎服务器上

  instance:
    instance-id: payment8001 #这是给eureka控制台调整主机名称的
    prefer-ip-address: true #显示ip地址
